[package]
name = "chatty"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "chatty_server"
path = "./src/server.rs"

[[bin]]
name = "chatty_client"
path = "./src/client.rs"

[dependencies]
bincode = "2.0.1"
chrono = "0.4.42"
crossterm = "0.29.0"
mio = { version = "1", features = ["net", "os-poll"] }
ratatui = { version = "0.29.0", features = ["unstable-rendered-line-info"] }
tui-textarea = "0.7.0"
self_update = "0.42.0"
