name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-windows-msvc:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build debug (on main pushes)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: cargo build

      - name: Build release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: cargo build --bin chatty_client --release

      - name: Rename binary with version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          $NEW_NAME="chatty_client-${{ github.ref_name }}-x86_64-pc-windows-msvc.exe"
          Rename-Item "target/release/chatty_client.exe" $NEW_NAME
        shell: pwsh

      - name: Release (create + upload)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: ChaTTY - ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: target/release/chatty_client-${{ github.ref_name }}-x86_64-pc-windows-msvc.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
